### ISSUE TITLE
Possible Typo

### ISSUE THREAD

**Issue by Koehler107B** [PetzoldLab/mcsf-git#1]
On the readme.md file, there is a phrase that says:

"In some cases one BMRB ID is linked to multiple PDB IDs and in some cases one BMRB ID is linked to multiple PDB IDs."

This is a redundancy and I believe the second portion is supposed to be of a switched order.

**Comment by lucubrator** [comment]
Nicely spotted @Koehler107B!

What I wanted to express was the possibility for:
 A. One BMRB ID to be linked to multiple PDB IDs
 B. One PDB ID to be linked to multiple BMRB IDs

I changed the passage to:

> In some cases, a many-to-many relationship may exist between BMRB IDs and PDB IDs, 
meaning a single BMRB ID might be linked to multiple PDB IDs, or vice versa. 
In such scenarios, the script selects the paired entry with the highest ID number, 
assuming it to be the most recent.
